package com.company;

public class Programmer {

    // Instance Variables - each instance of the class Programmer will have a copy these variables.
    // id - this will be autogenerated when added to the database.
    private int id;
    private String name;
    private String email;
    private String mobile;
    private String skills;
    private double salary;



    // this constructor does not accept an ID. Use this constructor when first creating objects. The Id will be generated
    // when the object is stored in the database - Auto-increment
    public Programmer(String n, String e, String m,  String sk, double sl) {
        this.name = n;
        this.email = e;
        this.mobile = m;
        this.skills = sk;
        this.salary = sl;
    }

    // Use this constructor when you are taking data from the database, it accepts an ID.
    public Programmer(int id, String n, String e, String m, String sk, double sl) {
        this.id = id;
        this.name = n;
        this.email = e;
        this.mobile = m;
        this.skills = sk;
        this.salary = sl;
    }

    public int getId()
    {
        return id;
    }

    public void setId(int id){
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }


    public String getSkills() {
        return skills;
    }

    public void setSkills(String skills) {
        this.skills = skills;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    // special method that will return a string version of the object, you should format and return everything
    @Override
    public String toString()
    {
        return "Programmer ID : " + id + " Programmer name : " + name + "\n" ;
    }
}
